### PR TITLE
Included records are now saved to store for pagination requests

### PR DESCRIPTION
**Pull request by Chilinot**
This PR also refactors the test suite to allow for functions to specify common tests that are shared between multiple actions.

The refactor is based on the following: https://blog.revathskumar.com/2018/07/jest-shared-tests.html

### CODE REVIEW

**Comment by Chilinot** [comment]
This PR does not implement the functionality for the two `loadNextPage` and `loadPreviousPage` actions. I leave that for someone else for now.

**Comment by Chilinot** [comment]
I have updated the PR to include the functionality for the `nextPage` and `previousPage` actions now as well.

**Comment by Chilinot** [comment]
I rebased the PR on the latest master branch

**Comment by CodingItWrong** [comment]
@Chilinot Thanks! The test refactoring seems helpful too.

**Comment by CodingItWrong** [comment]
@Chilinot This has been published as `0.1.5`

**Comment by Chilinot** [comment]
Awesome!

**Pull request merged**
