### PR TITLE
fix(relationships): fix one relationship to many empty

### PR DESCRIPTION
**Pull request by SancheZz**
**info**
[docs](https://jsonapi.org/format/#fetching-relationships-responses)
to-one relationship should return data = null
to-many relationship should return data = []

**subject**
At the moment, we get an error when destructuring an empty array [on line 328](https://github.com/reststate/reststate-vuex/blob/master/src/reststate-vuex.js#L328).

### CODE REVIEW

**Comment by CodingItWrong** [comment]
@SancheZz Thanks for this fix! Could you add a test covering it? Here's a similar test passing in a _present_ relationship; you could add a test passing in an empty relationship.

**Comment by SancheZz** [comment]
@CodingItWrong Thank you! :) I added a test for that fix. I have changed the update record behavior.  Old relationships will be removed first and then new relationships will be added from the record.

**Comment by CodingItWrong** [comment]
@SancheZz Thanks for adding this test!

I'd like to request one enhancement. On like 327 you're using the relationship name as the name of the resource, which works for your test and most basic cases, but is not always the case. For example, you might have a relationship named `authors`, but the resource name is `people`.

Instead, it's safer to look up the name of the resource from one of the records in the array. You can see me doing this here: https://github.com/reststate/reststate-vuex/pull/186/commits/3ed8ea4920fb23b11a8d4915947b20909124aad0#diff-602c4b25d8a2c1cae4aefd3464d69f51R354

If you add the following above your `dispatch` call to get the `type`, and use that to dispatch to instead, the test will still pass, and it'll handle more cases

```
const { data } = oldRecord.relationships[name];
let type;
if (Array.isArray(data)) {
  ({ type } = data[0]);
} else {
  ({ type } = data);
}
```

Another note: you first clear the old relationships, then store the new record, then store the new relationships. I think in the future I might work on changing the code so that we first store the record, then store the new relationships _or_ clear out a relationship that was empty. I experimented with doing this and it was tricky, so I see why you didn't do it that way. But if you know of any reasons for me _not_ to do it that way in the future, please let me know!

Thanks again for contributing. After you add the type lookup above, I can merge and do a release to include this fix.

**Comment by SancheZz** [comment]
@CodingItWrong Thank you very much! You are right! I need to use `relationship` and `type` of each resource which will be removed. I have added helper function `getRelationshipType` to get a type of a resource.
I think a new major or minor version should be contained a graph of resources. :) Each operation with the JSONAPI store should update the graph. :)

**Comment by CodingItWrong** [comment]
@SancheZz Nice helper function, I think I'll be able to use that elsewhere.

Good big-picture thoughts too; I'll think it over.

Thanks again for contributing! I'll release this shortly.

**Pull request merged**
